### PR TITLE
Create week-1 README.md

### PR DESCRIPTION
**Pull request by eliasmalik**
This is mostly to serve as a guide for the mentors, but also to summarise to the students what they should expect to cover in this session.

This is also intended as a rough guide for mentors in future weeks when they create READMEs for their weeks.

### CODE REVIEW

**Review by RanaAlqrenawi — APPROVED** [review]

**Comment by RanaAlqrenawi** [comment]
@mhmdshorafa @mohanagy @Alaa-Khattab  It's great if you review this guys! ✌️

**Comment by eliasmalik** [comment]
The second person to approve can merge it 🙏

**Review by mohanagy — COMMENTED** [review]
I had notice,
it's about installing the Ubuntu.
What happened took a lot of time, 
Due to the different core of laptops.
Due to this we waste a lot of time and at the end almost of them installed the Ubuntu as VM,
I think we need to find a solution maybe,
maybe extend the time,  I don't know

**Comment by eliasmalik** [comment]
@mohanagy are you saying some of them have Ubuntu on a VM instead of actually installed on their computer? I thought you said the opposite during our standup. Could you confirm please?

You may be right that it may be too optimistic to expect to get through all of this in one four hour session. But I think the attendees are aware that they should continue to work on the material during the rest of the week. 

So for example, we could say that the first 4-hour session is just to get Ubuntu installed, but that after that, on the other days (e.g. Saturday or some time before the next Thursday), they continue to work on the other exercises that we link to in this README (e.g. the command-line tutorial, or beginning Free Code Camp) without the mentors.

What do you think?

**Comment by mohanagy** [comment]
I didn't attend today to the startup  :grimacing:  
I think you mean Shurafa, not me.
And I'm with your suggestion.
cool

**Comment by RanaAlqrenawi** [comment]
@mohanagy yes, @mhmdshorafa said that about the girls who he installed the os to. So, I think it's fine right now, and we can take this in our consideration and do as @eliascodes said. I will create a gitter channel for the girls so we can push things their to them and make it clear that they need to check the stuff during the week and they are welcome to raise questions and ask for help even if it's not Thursday. Sounds good?

**Pull request merged**
